# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mx', '0004_auto_20190113_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='gray',
            field=models.FloatField(default=1.0),
        ),
    ]
