# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mx', '0006_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='is_selected',
            new_name='isselected',
        ),
    ]
