# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mx', '0007_auto_20190117_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='isselected',
            new_name='isselect',
        ),
    ]
